apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-hub-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-hub
  template:
    metadata:
      labels:
        app: api-hub
    spec:
      containers:
        - name: api-hub
          image: 13angs/al_iqraa_api_hub

---
apiVersion: v1
kind: Service
metadata:
  name: api-hub-srv
spec:
  selector:
    app: api-hub 
  ports:
    - name: api-container
      protocol: TCP
      targetPort: 5100
      port: 5100