apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-auth
  template:
    metadata:
      labels:
        app: api-auth
    spec:
      containers:
        - name: api-auth
          image: 13angs/al_iqraa_api_auth
          env:
          - name: COLLECTION_NAME
            value: "AL_IQRAA_AUTH_DB"
          - name: DATABASE_DOMAIN
            value: "db-auth-srv"
          - name: DATABASE_PORT
            value: "27017"
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY

---
apiVersion: v1 
kind: Service
metadata:
  name: api-auth-srv
spec:
  selector:
    app: api-auth 
  ports:
    - port: 5003
      name: api-auth
      targetPort: 5003
      protocol: TCP

