apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-auth
  template:
    metadata:
      labels:
        app: api-auth
    spec:
      containers:
        - name: api-auth
          image: 13angs/al_iqraa_api_auth

---
apiVersion: v1 
kind: Service
metadata:
  name: api-auth-srv
spec:
  selector:
    app: api-auth 
  ports:
    - port: 5003
      name: api-auth
      targetPort: 5003
      protocol: TCP

