# kubernetes rely on docker remote docker
# so you need to update the repo in dockerhub
# in order to update the local project
apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - "./infra/k8s/*"

build:
  local:
    push: false
  artifacts:
    - image: 13angs/al_iqraa_api_blog
      context: api/blog
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "api/blog/**/*.cs"
    
    - image: 13angs/al_iqraa_api_hub
      context: api/hub
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "api/hub/**/*.cs"
    
    - image: 13angs/al_iqraa_api_auth
      context: api/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual: 
          - dest: .
            src: "api/auth/**/*.ts"

    - image: 13angs/al_iqraa_api_container
      context: app
      docker:
        dockerfile: ./dockerfiles/Dockerfile.container
      sync:
        manual:
          - dest: .
            src: "app/container/**/*.js"
    
    - image: 13angs/al_iqraa_app_fragment
      context: app
      docker:
        dockerfile: ./dockerfiles/Dockerfile.fragment
      sync:
        manual:
          - dest: .
            src: "app/fragment/**/*.js"

    - image: 13angs/al_iqraa_app_dashboard
      context: app
      docker:
        dockerfile: ./dockerfiles/Dockerfile.dashboard
      sync:
        manual:
          - dest: .
            src: "app/dashboard/**/*.js"
  