apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-container-depl 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-container
  template:
    metadata:
      labels:
        app: app-container
    spec:
      containers:
        - name: app-container
          image: 13angs/al_iqraa_app_container
          env:
            - name: PRODUCTION_DOMAIN
              value: http://al-iqraa.com

---
apiVersion: v1
kind: Service
metadata:
  name: app-container-srv 
spec:
  selector:
    app: app-container
  ports:
    - port: 3000
      name: app-container
      protocol: TCP
      targetPort: 3000