apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-home-depl 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-home
  template:
    metadata:
      labels:
        app: app-home
    spec:
      containers:
        - name: app-home
          image: 13angs/al_iqraa_app_home
          env:
            - name: PRODUCTION_DOMAIN
              value: http://al-iqraa.com

---
apiVersion: v1
kind: Service
metadata:
  name: app-home-srv 
spec:
  selector:
    app: app-home
  ports:
    - port: 3000
      name: app-home
      protocol: TCP
      targetPort: 3000