version: '3.8'

services:
  container:
    image: 13angs/al_iqraa_app_container:latest
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.container
    ports:
      - "3000:80"

  fragment:
    image: 13angs/al_iqraa_app_fragment:latest
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.fragment
    ports:
      - "3001:80"

  dashboard:
    image: 13angs/al_iqraa_app_dashboard:latest
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.dashboard
    ports:
      - "3002:80"