apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
  - host: al-iqraa.com
    http:
      paths:
        - path: /api/v1/?(.*)
          pathType: Exact
          backend:
            service:
              name: blog-srv
              port:
                number: 5000
          
          