apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
  - host: al-iqraa.com
    http:
      paths:
        - path: /api/v1/blogs/?(.*)
          pathType: Prefix
          backend:
            service:
              name: blog-srv
              port:
                number: 5000
        
        - path: /api/v1/auth/?(.*)
          pathType: Prefix
          backend:
            service:
              name: api-auth-srv
              port:
                number: 5003
        
        - path: /hubs
          pathType: Prefix
          backend:
            service:
              name: api-hub-srv
              port:
                number: 5100

        - path: /dashboard
          pathType: Prefix
          backend:
            service:
              name: app-dashboard-srv
              port:
                number: 3002

        - path: /fragment
          pathType: Prefix
          backend:
            service:
              name: app-fragment-srv
              port:
                number: 3001

        - path: /
          pathType: Prefix
          backend:
            service:
              name: app-container-srv
              port:
                number: 3000
          
          